
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#D9D9D9")


canvas = Canvas(
    window,
    bg = "#D9D9D9",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    600.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_ajutor.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    activebackground="#D9D9D9",
    bg="#D9D9D9"
)
button_1.place(
    x=723.0,
    y=567.0,
    width=61.0,
    height=26.012451171875
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_1 = canvas.create_image(
    400.0,
    300.0,
    image=image_image_1
)

canvas.create_rectangle(
    -4.0,
    558.0,
    800.0,
    562.0,
    fill="#C4C4C4",
    outline="")

canvas.create_text(
    323.0,
    570.0,
    anchor="nw",
    text="™ F230-OCR",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    14.0,
    571.0,
    anchor="nw",
    text="©2025 Rareș Anghel",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    320.0,
    18.0,
    anchor="nw",
    text="F230-OCR",
    fill="#000000",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    330.0,
    59.0,
    anchor="nw",
    text="Rapoarte",
    fill="#000000",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    44.0,
    101.0,
    anchor="nw",
    text="Perioada de distribuire",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    44.0,
    215.0,
    anchor="nw",
    text="Total - X formulare",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    44.0,
    271.0,
    anchor="nw",
    text="Cele mai multe formulare sunt în:",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    56.0,
    139.0,
    anchor="nw",
    text="1 an   \n2 ani",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    56.0,
    301.0,
    anchor="nw",
    text="1. Judetul A - X formulare\n2. Judetul B - Y formulare\n3. Judetul C - Z formulare",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    138.0,
    139.0,
    anchor="nw",
    text="X formulare\nX formulare",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    121.0,
    139.0,
    anchor="nw",
    text="-\n-",
    fill="#000000",
    font=("Inter", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
